### ISSUE TITLE
plot checklist

### ISSUE THREAD

**Issue by ellackane** [mwvgroup/SN-Spectral-Evolution#59]
- [ ] evolution vs. phase
- [x] branch plot
- [ ] feature strength vs. host galaxy redshift
- [ ] feature strength vs. host galaxy mass
- [ ] feature strength vs. host galaxy SFR
- [ ] feature strength vs. host galaxy age
- [ ] feature strength vs. ejection vel
- [ ] feature strength vs. distance from host
- [ ] feature velocity vs. host galaxy redshift
- [ ] feature velocity vs. host galaxy mass
- [ ] feature velocity vs. host galaxy SFR
- [ ] feature velocity vs. host galaxy age
- [ ] feature velocity vs. distance from host
- [ ] binned by high mass vs. low mass, low SFR vs. high SFR
- [ ] number of observation vs. phase (histogram)
- [ ] ejection velocity vs. phase
- [ ] pew vs. stretch and color excess 
- [ ] ejection velocity vs. strength and color excess
- [ ] Zhang plots?
